### ISSUE TITLE
IAOC directions to NomCom

### ISSUE THREAD

**Issue by jlivingood** [IASA2/NomCom-Guidance#3]
The IAOC needs to tell the NomCom not to fill IAOC slots

**Comment by coopdanger** [comment]
Actually I was incorrect about this. No directions need to or can be given about the IAOC slot; it is at the NomCom's discretion to not fill the open slot until we update RFC 4071 or RFC 7437.

**Comment by jlivingood** [comment]
We have concurrence on the list as well. Per John Levine on the WG mailing list: Under RFC 7437 the Nomcom does not have discretion about whether to fill a vacancy. IAOC will notify Nomcom if there's a vacancy. We all realize that the IAOC is likely to disappear by the end of the year, so there's no point to putting a lot of effort into this either way.
